# set -g set-titles on
# set -g set-titles-string "#W"

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# enable scroll with mouse
set -g mouse on 

# vi mode
set-window-option -g mode-keys vi

set -sg escape-time 10

# Setup 'v' to begin selection, just like Vim
bind-key -T copy-mode-vi v send-keys -X begin-selection

# Setup 'y' to yank (copy), just like Vim
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

set-option -g history-limit 5000
